version: '3.9'
services:
  navidrome:
    container_name: navidrome
    image: 'deluan/navidrome:latest'
    restart: unless-stopped
    ports:
      - '4533'
    labels:
      - traefik.enable=true
      - traefik.http.routers.navidrome.rule=Host(`navidrome.richardxiong.com`)
    volumes:
      - 'data:/data'
      - 'music:/music:ro'

  navidrome-manager:
    container_name: navidrome-manager
    image: 'registry.richardxiong.com/navidrome-manager:latest'
    restart: unless-stopped
    ports:
      - '3005'
    labels:
      - traefik.enable=true
      - traefik.http.routers.navidrome-manager.rule=Host(`navidrome-manager.richardxiong.com`)
    environment:
      - ADMIN_KEY=$ADMIN_KEY
    volumes:
      - 'music:/music'
